# Generated by Django 5.1.4 on 2024-12-19 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_rtchats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessages", options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="users_online",
            field=models.ManyToManyField(
                blank=True, related_name="online_in_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupmessages",
            name="created",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
